### ISSUE TITLE
Build error with json-c 0.13

### ISSUE THREAD

**Issue by holomorph** [newsboat/newsboat#98]
When building 5d84bc17 on Arch:
```
g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.2-37-g5d84\" -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -DHAVE_OPENSSL=1 -o src/oldreader_api.o -c src/oldreader_api.cpp
g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.2-37-g5d84\" -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -DHAVE_OPENSSL=1 -o src/feedhq_api.o -c src/feedhq_api.cpp
src/oldreader_api.cpp: In member function ‘virtual std::vector<std::pair<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > > > newsboat::oldreader_api::get_subscribed_urls()’:
src/oldreader_api.cpp:137:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    for (int i = 0; i < array_list_length(categories); i++) {
                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:113: src/oldreader_api.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Minoru** [comment]
Thanks for the report! Turns out json-c changed the return type from [`int`](https://github.com/json-c/json-c/blob/2849650f1130f97621e39ff4cb5b6d3da0e97653/arraylist.h#L53) to [`size_t`](https://github.com/json-c/json-c/blob/acbcc062f9c114f7b2a63b792897fdfffed71d14/arraylist.h#L46) in their `0.13` release. Very interesting change; I wonder how I am supposed to work around it: if I change the loop to `size_t`, Newsboat won't compile with 0.12, and if I use `int`, it won't compile with 0.13 :)

Let me sleep a bit and I'll figure something out.

**Comment by Minoru** [comment]
Ah, okay, they have macros with version [in `json_version.h`](https://github.com/json-c/json-c/blob/master/json_c_version.h#L15). I'll update the code to use those for conditional compilation tomorrow.

**Comment by holomorph** [comment]
Cheers o/

**Comment by Minoru** [comment]
Should be okay now.
