### ISSUE TITLE
error while loading shared libraries: libjson-c.so.3 Ubuntu 20.04

### ISSUE THREAD

**Issue by ilakast** [newsboat/newsboat#1351]
I am afraid I cannot provide the version (it is not 2.18 from the repositories, but a newer version) because newsboat fails to load since it appears that libjson-c3 has been replaced with libjson-c4 in Ubuntu 20.04. Newsboat was working fine prior to me upgrading from 18.04 to 20.04.

**Comment by Minoru** [comment]
There are a couple ways for you to fix this:

1. build Newsboat against the library you have;
2. install the library that the old build of Newsboat wants;
3. install Newsboat from the Snap Store, which carries a newer version that Ubuntu APT repos.

How did you install a newer version on Ubuntu 18.04? It's probably easiest for you to repeat the same process on Ubuntu 20.04.

**Comment by ilakast** [comment]
Thank you. I compiled from source on Ubuntu 18.04. I took your suggestion, but `make` stops with the following error which I cannot decipher
`g++ -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Itarget/cxxbridge/libnewsboat-ffi/src/ -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR='"/usr/local/share/locale"' -I/usr/include/x86_64-linux-gnu -I/usr/include/libxml2 -I/usr/include/json-c -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -o src/feedlistformaction.o -c src/feedlistformaction.cpp
src/feedlistformaction.cpp: In member function ‘virtual bool newsboat::FeedListFormAction::process_operation(newsboat::Operation, bool, std::vector<std::__cxx11::basic_string<char> >*)’:
src/feedlistformaction.cpp:303:34: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  303 |      v->show_error(strprintf::fmt(_("Browser returned error code %i"), *exit_code));
      |                    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/feedlistformaction.cpp:277:34: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  277 |      v->show_error(strprintf::fmt(_("Browser returned error code %i"),
      |                    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  278 |        exit_code.value()));
      |        ~~~~~~~~~~~~~~~~~~         
cc1plus: all warnings being treated as errors
make: *** [Makefile:172: src/feedlistformaction.o] Error 1
`

**Comment by Minoru** [comment]
This warning comes from a third-party library we use, and it's pretty innocuous. I think we know what we're doing there :)

We turn warnings into errors to nudge users into reporting these things, so thanks for doing exactly that! Looks like we are not seeing this in CI because we don't compile with optimizations enabled on Ubuntu 20.04. I'll think what should be done about this.

Meanwhile, you can turn this error back into a warning by running `CXXFLAGS="-Wno-error=maybe-uninitialized" make`.

**Comment by ilakast** [comment]
I cannot thank you enough; I would have never been able to sort this out without your help. Installed fine now. Happy days

**Comment by Minoru** [comment]
Cool, glad you got it working! By the way, the warnings that you mentioned are now fixed by https://github.com/newsboat/newsboat/pull/1347, so 2.22 release won't have them. Funny that once you've reported them, our CI started displaying them as well :)

**Comment by ilakast** [comment]
I need to reopen this issue. Trying to install 2.22, I now get two errors:

`cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]` and `src/itemlistformaction.cpp:196:33: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  196 |     v->show_error(strprintf::fmt(_("Browser returned error code %i"), *exit_code));
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/itemlistformaction.cpp:179:33: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  179 |     v->show_error(strprintf::fmt(_("Browser returned error code %i"), *exit_code));
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I tried to adapt the flag for this warning to be ignored, using 
`CXXFLAGS="-Werror=maybe-uninitialized"` to no avail.

**Comment by ilakast** [comment]
I need to reopen this issue. Trying to install 2.22, I now get two errors:

`cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]` and `src/itemlistformaction.cpp:196:33: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  196 |     v->show_error(strprintf::fmt(_("Browser returned error code %i"), *exit_code));
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/itemlistformaction.cpp:179:33: error: ‘*((void*)& exit_code +1)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  179 |     v->show_error(strprintf::fmt(_("Browser returned error code %i"), *exit_code));
      |                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I tried to adapt the flag for this warning to be ignored, using 
`CXXFLAGS="-Werror=maybe-uninitialized"` to no avail.

**Comment by Minoru** [comment]
Reproduced. Please compile with `CXXFLAGS="-Wno-error"` to turn these errors back into warnings. Sorry they keep popping up, and thanks once again for reporting them!

<hr/>

Mere `CXXFLAGS="-Wno-error=maybe-unitialized"` doesn't work for a fairly bizarre reason: GCC doesn't support `-Wno-unknown-warning-option`, but doesn't complain about it unless there are other diagnostics. So when `-Wmaybe-unitialized` is triggered, GCC also prints a message about `-Wno-unknown-warning-option`. In the presence of `-Werror`, both messages are turned into errors. Even if we use `-Wno-error=maybe-unitialized` to demote that one back to the "warning" level, the message about the unsupported option is still treated as an error. I didn't find a way to selectively demote it to a warning, so I have to recommend `-Wno-error`.

I think this whole issue is caused by https://github.com/newsboat/newsboat/commit/f7f6d61cbdd5062e4bf3370e90f5f580ec12f1d6. My second assumption there is not entirely correct: we run newer compilers with `-O3`, not the default `-O2`, and so get a different set of warnings. I'll submit a PR that re-enables `-O2` in all builds.

I'll also go ask the maintainer of optional-lite if this warning can be fixed upstream.

**Comment by ilakast** [comment]
Confirming solution works. Thank you once again!

**Comment by Minoru** [comment]
> I'll also go ask the maintainer of optional-lite if this warning can be fixed upstream.

I'm pedalling back on this because I can't write a simple reproducer. Apparently this can only be triggered with a complex enough code, where optimizer no longer sees enough of the program to decide if the variable is initialized or not. I don't think this is something that optional-lite can fix, so I'm not going to file an issue with them.
