### ISSUE TITLE
FTB on Cygwin because wchar_t is only 16 bits wide

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#151]
**Newsboat version (copy from `newsboat -v`)**: 2.11-3-g52fe

Reported by akemot on IRC.

Fails to compile on Cygwin with GCC 6.4.0:
```
g++ -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.11-3-g52fe-dirty\" -I/../../include/libxml2 -I/usr/local/include -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE  -o filter/Scanner.o -c filter/Scanner.cpp
filter/Scanner.cpp: In member function ‘void Scanner::AddCh()’:
filter/Scanner.cpp:504:9: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  if (ch != Buffer::EoF) {
      ~~~^~~~~~~~~
filter/Scanner.cpp: In member function ‘Token* Scanner::NextToken()’:
filter/Scanner.cpp:592:40: error: comparison is always true due to limited range of data type [-Werror=type-limits]
    if (ch <= L'!' || (ch >= L'#' && ch <= 65535)) {AddCh(); goto case_4;}
                                     ~~~^~~~~~~~
cc1plus: all warnings being treated as errors
```

The output of
```
$ g++ -E -dD -xc++ newsboat.cpp | egrep '__WCHAR_(TYPE|MAX)'
```
is
```
#define __WCHAR_TYPE__ short unsigned int
#define __WCHAR_MAX__ 0xffff
#define WCHAR_MAX __WCHAR_MAX__
newsboat.cpp:3:17: fatal error: rss.h: No such file or directory
 #include <rss.h>
                 ^
compilation terminated.
```

So, as other sources on the Internet point out, `wchar_t` is 16-bit on Windows.

**Comment by Minoru** [comment]
Not clear how to proceed here. Are we in the wrong, is Windows in the wrong, [are *everybody* in the wrong](https://www.gnu.org/software/libunistring/manual/html_node/The-wchar_005ft-mess.html)? Need to read up on `wchar_t` and find out how other projects deal with this.

**Comment by ptytb** [comment]
[cygwin.diff.txt](https://github.com/newsboat/newsboat/files/1855487/cygwin.diff.txt)

There're the changes needed to make Newsboat compile and work just fine under Cygwin.

**Comment by Minoru** [comment]
Wow; thank you very much! Are you interested in submitting that as a pull request?

* I'll accept `msgfmt.py` change if it's wrapped in some conditional; e.g. [Git uses `NO_MSGFMT_EXTENDED_OPTIONS`](https://stackoverflow.com/a/18604066/2350060). You can look at `PROFILE` for an example of how to do this;
* I withhold my judgement on `union` thing for now—I do need to read up on `wchar_t` problems first;
* commenting out `assert`s is very suspicious, as they're there for a reason. Would you be interested in uncommenting them and showing a log that leads up to them triggering? You can use `--log-file=newsboat.log --log-level=6` to obtain the log;
* the correct way to fix the `const`-ness thing is to add new entry to `#if` that precedes it. Cygwin must have a define that we could use there. In fact, you can use that same technique to change `whar_t` to `int`, if that works.

**Comment by ptytb** [comment]
Please use 7zip to unpack the log:
[newsboat.log.7z.log](https://github.com/newsboat/newsboat/files/1866520/newsboat.log.7z.log)
