### PR TITLE
Add missing newsboat namespace

### PR DESCRIPTION
**Pull request by carno**
Fix compilation issue:
```cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10-74-g7901\" -I/usr/include/x86_64-linux-gnu -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -o src/download.o -c src/download.cpp
rss/atom_parser.cpp: In member function ‘rsspp::item rsspp::atom_parser::parse_entry(xmlNode*)’:
rss/atom_parser.cpp:106:9: error: ‘utils’ has not been declared
     if (utils::is_valid_podcast_type(type)) {
         ^~~~~
```
introduced in ef929a9c3bda2f58ce300ac2e9d5e4a4159026c9

### CODE REVIEW

**Comment by Minoru** [comment]
Oops! Sorry about that, and thanks for fixing it :) How did you notice it so fast?

Will merge once Travis is done.

**Comment by carno** [comment]
I just did a random git pull and make :D waiting for F1 race to start
